# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
widgets:
  - about         # See also: `about_content`
  - archive
  - recent_posts
  - category
  - tag
  #- tagcloud

about_widget_content: >
  <p>Hi, I am <b>Matt Guo</b></p>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: images/favicon.ico
twitter_id:
google_plus:
fb_admins:
fb_app_id:
